id: I999FE42F
legacy_id: P005491
ocr_import_info:
  bdrc_scan_id: W3PD381
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T23:23:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:50:39.723998+00:00'
last_modified: 2022-09-04 01:50:50.570874
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD381
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3PD381
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱེས་ཆེན་གྱི་བཞུད་ལམ། （རྟོགས་བརྗོད་མདུན་ལེགས་མའི་དཔེ་འཁྲིད）སྒྲ་བཤུས།
statistics:
  ocr_word_mean_confidence_index: 0.9463408413572519
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I4PD4640:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4640
      total_pages: 266
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD4640.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9463408413572519
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
