id: P005491
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:53:38.900417
source_metadata:
  id: bdr:W3PD381
  title: སྐྱེས་ཆེན་གྱི་བཞུད་ལམ། （རྟོགས་བརྗོད་མདུན་ལེགས་མའི་དཔེ་འཁྲིད）སྒྲ་བཤུས།
  author: ''
  volumes:
    b30b3e9afee8480fa425f1fdefdfae0e:
      image_group_id: I4PD4640
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
